"use client";

import { useState } from "react";
import type { Organization, User } from "../lib/types";

type Props={user:User;organizations:Organization[];loading:boolean;error:string;onSelect:(organization:Organization)=>void;onCreate:(input:{name:string})=>void;onLogout:()=>void};

export function OrganizationDashboard({user,organizations,loading,error,onSelect,onCreate,onLogout}:Props){
  const [name,setName]=useState("");const canCreate=user.role==="counselor_admin";
  return <main className="main dashboard"><header className="product-header"><div><span className="eyebrow">NIST CSF 2.0 / ORGANIZATIONS</span><h1>Client organizations</h1><p className="muted">Choose a client workspace before creating or continuing a project.</p></div><div className="identity-block"><span className="role-chip">{user.role.replaceAll("_"," ")}</span><strong>{user.name}</strong><button className="text-button" onClick={onLogout}>Sign out</button></div></header>{error&&<div className="error" role="alert">{error}</div>}<section aria-labelledby="organizations-heading"><div className="section-heading"><span className="section-index">CLIENT INDEX</span><h2 id="organizations-heading">Organizations</h2></div>{loading?<div className="panel muted">Loading organizations…</div>:organizations.length===0?<div className="empty-state">No organizations yet.</div>:<div className="organization-grid">{organizations.map((organization,index)=><article className="organization-card" key={organization.id}><div className="organization-number">{String(index+1).padStart(2,"0")}</div><div><h3>{organization.name}</h3><p className="muted">Client organization</p></div><button className="secondary" aria-label={`Open ${organization.name}`} onClick={()=>onSelect(organization)}>Open workspace</button></article>)}</div>}</section>{canCreate&&<section className="panel create-organization" aria-labelledby="create-organization"><div><span className="section-index">NEW CLIENT</span><h2 id="create-organization">Create organization</h2><p className="muted">Projects and stakeholders will live inside this workspace.</p></div><form className="form" onSubmit={event=>{event.preventDefault();onCreate({name:name.trim()});setName("")}}><label className="field"><span>Organization name</span><input required value={name} onChange={event=>setName(event.target.value)}/></label><button className="primary">Create organization</button></form></section>}</main>;
}
