import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { expect, test, vi } from "vitest";
import { OrganizationWorkspace } from "./OrganizationWorkspace";
import type { Organization, Project, User } from "../lib/types";

const counselor:User={id:"user-1",organizationID:null,name:"Consultant",email:"c@example.com",userType:"counselor",role:"counselor",status:"active"};
const orgAdmin:User={id:"user-2",organizationID:"org-1",name:"Customer Admin",email:"a@acme.test",userType:"stakeholder",role:"org_admin",status:"active"};
const organization:Organization={id:"org-1",name:"Acme",slug:"acme",type:"client"};
const project:Project={id:"project-1",organizationID:"org-1",organizationName:"Acme",name:"Readiness",slug:"readiness",status:"setup",createdAt:"2026-08-06T03:00:00Z"};

test("counselor creates a project in the selected organization",()=>{const onCreate=vi.fn();render(<OrganizationWorkspace user={counselor} organization={organization} projects={[project]} users={[orgAdmin]} loading={false} error="" onBack={vi.fn()} onOpen={vi.fn()} onCreateProject={onCreate} onDeleteProject={vi.fn().mockResolvedValue(undefined)} onInvite={vi.fn()}/>);fireEvent.change(screen.getByLabelText(/project name/i),{target:{value:"  Gap Review  "}});fireEvent.click(screen.getByRole("button",{name:/create project/i}));expect(onCreate).toHaveBeenCalledWith({name:"Gap Review"})});
test("organization admin can invite but cannot create projects",()=>{render(<OrganizationWorkspace user={orgAdmin} organization={organization} projects={[project]} users={[orgAdmin]} loading={false} error="" onBack={vi.fn()} onOpen={vi.fn()} onCreateProject={vi.fn()} onDeleteProject={vi.fn().mockResolvedValue(undefined)} onInvite={vi.fn()}/>);expect(screen.queryByRole("button",{name:/create project/i})).toBeNull();expect(screen.getByRole("button",{name:/create invitation/i})).toBeTruthy()});

test("labels the projects and stakeholders sections",()=>{render(<OrganizationWorkspace user={counselor} organization={organization} projects={[project]} users={[orgAdmin]} loading={false} error="" onBack={vi.fn()} onOpen={vi.fn()} onCreateProject={vi.fn()} onDeleteProject={vi.fn().mockResolvedValue(undefined)} onInvite={vi.fn()}/>);expect(screen.getByRole("region",{name:/projects/i})).toBeTruthy();expect(screen.getByRole("region",{name:/stakeholders/i})).toBeTruthy()});

test("requires confirmation before deleting a project",async()=>{const onDelete=vi.fn().mockResolvedValue(undefined);render(<OrganizationWorkspace user={counselor} organization={organization} projects={[project]} users={[orgAdmin]} loading={false} error="" onBack={vi.fn()} onOpen={vi.fn()} onCreateProject={vi.fn()} onDeleteProject={onDelete} onInvite={vi.fn()}/>);fireEvent.click(screen.getByRole("button",{name:"Delete Readiness"}));expect(screen.getByRole("dialog",{name:/delete readiness/i})).toBeTruthy();const confirm=screen.getByRole("button",{name:/delete project/i}) as HTMLButtonElement;expect(confirm.disabled).toBe(true);fireEvent.change(screen.getByLabelText("Type Readiness to confirm"),{target:{value:"Readiness"}});fireEvent.click(confirm);await waitFor(()=>expect(onDelete).toHaveBeenCalledWith(project))});

test("shows a project deletion error and keeps the confirmation open",async()=>{const onDelete=vi.fn().mockRejectedValue(new Error("Could not delete project"));render(<OrganizationWorkspace user={counselor} organization={organization} projects={[project]} users={[orgAdmin]} loading={false} error="" onBack={vi.fn()} onOpen={vi.fn()} onCreateProject={vi.fn()} onDeleteProject={onDelete} onInvite={vi.fn()}/>);fireEvent.click(screen.getByRole("button",{name:"Delete Readiness"}));fireEvent.change(screen.getByLabelText("Type Readiness to confirm"),{target:{value:"Readiness"}});fireEvent.click(screen.getByRole("button",{name:/delete project/i}));expect((await screen.findByRole("alert")).textContent).toContain("Could not delete project");expect(screen.getByRole("dialog",{name:/delete readiness/i})).toBeTruthy()});
